### ISSUE TITLE
Segmentation issue with single(same) user on multiple device

### ISSUE THREAD

**Issue by devalchauhan** [infobip/mobile-messaging-sdk-ios#11]
**Description:**  We are facing one issue with segmentation, which is explained below in form of what we want to achieve(requirement) and what we have configured to achieve the same.

**Requirement:** we want to receive notification based on installation configuration for single(same) user on multiple device.

**Example:** 
* One User: **User1**
* Two Devices: **Device1,Device2**
* Two Segments: **service-notification,transaction**
**Device1:** User1 is configured to receive(ON) transaction notification on Device1
**Decice2:** User1(**same user**) is configured not to receive(OFF) transaction notification on Device2

#### Now if we launch notification for transaction(segment)
**Actual Result:**  Device1 and Device2 both receives the notification.
**Expected Result:** Device1 should receive notification, but Device2 should not receive that notification

**Configuration:** we have used installation custom attribute to differentiate between two segment
* service-notification (true/false) : installation custom attribute 
* transaction(true/false) : installation custom attribute

**Attachement:** [configuration screenshot]

Kindly consider attached screenshot to check configuration which we have applied.

Please let me know if I am missing anything or not implementing it in the correct way.

Thank You,
Deval 

[configuration screenshot]:https://prnt.sc/mptfle

**Comment by kas-kad** [comment]
# Please fill out the following form to help us to resolve you issue faster.

* MobileMessaging SDK version: [FILL THIS OUT]
* Xcode version: [FILL THIS OUT]
* Your application language: [FILL THIS OUT. Objective-C or Swift, for Swift - specify which the version]
* Cocoapods version: [FILL THIS OUT. Not sure which version you are on? - Use a terminal command: 'pod --version']

**Comment by devalchauhan** [comment]
Hello @kas-kad ,
* MobileMessaging SDK version: [FILL THIS OUT]
* Xcode version: [FILL THIS OUT]
* Your application language: [FILL THIS OUT. Objective-C or Swift, for Swift - specify which the version]
* Cocoapods version: [FILL THIS OUT. Not sure which version you are on? - Use a terminal command: 'pod --version']

**Comment by devalchauhan** [comment]
Hello @kas-kad,

I really appreciate your pro-active response, kindly find requested information as per below.
* MobileMessaging SDK version: 5.1.8
* Xcode version: 10.1
* Your application language: swift 4.2
* Cocoapods version: pod 'MobileMessaging', '~> 5.1.8'

Thank You,
Deval

**Comment by kas-kad** [comment]
Hello @devalchauhan, thanks for the details. I'll take a look and revert to you shortly.

**Comment by kas-kad** [comment]
@devalchauhan can you please refer to a particular segment? I need a link for example https://portal.infobip.com/people/segments/11.

**Comment by devalchauhan** [comment]
@kas-kad  kindly find the segment URL as per below, https://portal.infobip.com/people/segments/11

**Comment by kas-kad** [comment]
Hello, @devalchauhan 
thank you for the detailed information. Segmentation by installation custom attributes is currently under development and will be available in 2 weeks. I'll revert to you when it's ready.

**Comment by devalchauhan** [comment]
Hello @kas-kad 

Thank you very much for your response, I can understand. 
Could you please help me out in achieving desired functionality? I just need minimal information if you can provide. Please consider **Requirement:** section to understand my desired functionality requirements.

Thanks,
Deval

**Comment by kas-kad** [comment]
As I mentioned before, this functionality cannot be done at the moment since the segmentation feature is in development process now. It will be done in 2 weeks.

**Comment by nsustavov** [comment]
Hi @devalchauhan, 
the particular issue currently is related only for campaigns from [Portal](https://portal.infobip.com) and when you use installation custom attributes. 

I completely understand your requirements to have separate subscriptions possibility for each of the particular user and complications you're facing in tests over Portal. 
It will be fixed, so that your segments created by installation custom attributes parameters would trigger the message only to that particular device of the user where subscription is made, rather than all devices of the particular user. 

Just to mention for your information as well that our platform can support shared data between several devices of the particular user, for example common subscriptions which will be applicable to all devices. 

However, apart of previously stated comments there is planned fix of the issue (_targeting segments by installation custom attributes_) in Portal in the next upcoming 2 weeks I can suggest you in meanwhile to perform a couple of tests over API POST request for your specific scenario. 
As I know one of your scenarios is transactional traffic which is supposed to be triggered from your external system. 

For case of transaction or any other trigger based traffic over API we recommend to use our [API with fallbacks](https://dev.infobip.com/omni-channel/push-example), so that you can ensure the message is delivered to end user even if user isn't present on mobile or offline. 
Steps are pretty simple but add a couple of additional parameters in step 2: 
1) create scenario for fallback, if you don't need any fallback for now, just leave only information about app code to be used in the scenario. 
2) send a message 
- request for sending messages may have not only "phoneNumber" but also "pushExternalUserId". 
- to use targeting by specific subscription on the specific device of the specific user use parameter "deviceSubscriptions". For example:
`
...
{
      "to":{
        "phoneNumber": "79210000000",
        "pushExternalUserId":"my_user_id"
      }
...
"push": {
    "text": "This PUSH message will test.",
    "deviceSubscriptions": ["marketing"],
    "validityPeriod": 90,
        "validityPeriodTimeUnit": "SECONDS"
  },
...`

Expected behaviour to send push notification to devices associated with "my_user_id" and only those devices that do have subscription to "marketing" messages. 
"phoneNumber" is optional and if your created scenario contains SMS channel for fallback, then automatic fallback will happen in case push message isn't delivered within "validityPeriod".

In case you'd need any additional clarification for API call tests, feel free to reach us our to support@infobip.com, so that our engineers could give you recommendations precisely to your case. 

As I said at the beginning, 
targeting segments over Portal with installation user data with the case how you described will be fixed pretty soon. Hope on your understanding, we remain for your questions. 

Nikolay, 
Product Owner, Infobip Mobile App Messaging.

**Comment by devalchauhan** [comment]
Hello @nsustavov and @kas-kad,

I really appreciate your prompt response. We can understand your concern and will be waiting for your fix to fulfill our business requirement. 

Thanks,
Deval

**Comment by tjuric** [comment]
Hi @devalchauhan,
Please, retest your use case. Targeting segments over Portal with installation user data should've been fixed.

Regards,
Tereza

**Comment by devalchauhan** [comment]
Hello @tjuric,

Thank you very much for the updates, will verify and let you know for the same.

Thanks,
Deval

**Comment by devalchauhan** [comment]
Hello @tjuric  

Verified and working as expected, thank you so much for the help @tjuric  @kas-kad @nsustavov 

Thanks,
Deval
