### ISSUE TITLE
Intermittent issue: NO_REGISTRATION 

### ISSUE THREAD

**Issue by akshardarji** [infobip/mobile-messaging-sdk-ios#15]
Hello @kas-kad,

We are updating externalUserId using personalize, once it's successfully personalized we are doing few installation configuration segments value changes(value either true/false).

we have tried with below functions to set customAttribute value:
```
func setInstallationConfiguration(isEnabled: Bool){
            MobileMessaging.fetchInstallation { (installationObj, error) in
                let subscriptions = String(isEnabled ? Strings.kTrue : Strings.kFalse)
                installationObj?.isPushRegistrationEnabled = isEnabled
                installationObj?.customAttributes = ["service-notification": subscriptions as NSString, "transactions-notifications": subscriptions as NSString]
                MobileMessaging.saveInstallation(installationObj!)
                { (error) in
                    if error != nil {
                        debugPrint(error.debugDescription)
                    }else {
                         // Successfully Executed ...
                    }
                }
            }
        }
```

We got following error sometimes while `saveInstallation` : 

> "Registration does not exist\" UserInfo={NSLocalizedDescription=Registration does not exist, messageId=NO_REGISTRATION, text=Registration does not exist}

As per our finding let me provide you steps: 
1. We trying to personalize to update externalUserId
2. On the success of personalized, we will try to update customAttribute using saveInstallation. 
3. On the call of saveInstallation, sometimes it got failed and we got an error which I have mention above. 
4. In this steps externalUserId shows update from `MobileMessaging SDK` as we got from `MobileMessaging.getUser().externalUserId` but don't know why shows externalPersonId nil on the portal. (You can find screenshot [here](https://prntscr.com/ochuba))

Kindly look into this as earliest.

Thanks

* MobileMessaging SDK version: [5.2.3]
* Xcode version: [10.1]
* Your application language: [Swift-4]
* Cocoapods version: [Pod Version - 1.5.3]

**Comment by kas-kad** [comment]
Hello, do use forceDepersonalize argument?

**Comment by akshardarji** [comment]
Yes, We have used below personalise method so there we have `forceDepersonalize` argument.

```
MobileMessaging.personalize(forceDepersonalize: true, userIdentity: userIdentity!, userAttributes: MobileMessaging.getUser(), completion: { (error) in   
       print("Completion")
})
```

**Comment by kas-kad** [comment]
At which moment do you call MobileMessaging.personalize? How do you define when is it time to call it?

**Comment by akshardarji** [comment]
We are personalize the user till externalUserId successfully updated from our side. Once we got updated externalUserId using `MobileMessaging.getUser().externalUserId` afterwards we only setting customAttribute using saveInstallation method. 

Because if we do personalise again and again for same data it doesn't make sense to me.

**Comment by kas-kad** [comment]
I've investigated the issue and found a rare issue related to race between registration update and installation data fetching. Could you pls try to update the MM SDK to version 5.2.6 and uninstall-install the application.

**Comment by akshardarji** [comment]
@kas-kad Sure. Thanks for your quick update.
Let me upgrade release `Ver. 5.2.6` and will update you once we are done with testing phase so we'll get back to you soon.

**Comment by akshardarji** [comment]
@kas-kad 

I would like to appreciate for your patience and support for this issue. 
 
We have done with our testing and we have encountered the minor following error while trying to personalizing the externalUserId hence can you look into it and let me know your findings on the same. 

>  - some : Error Domain=com.mobile-messaging Code=1 "The application instance is not registered on the server yet. The registration will be performed eventually. Subscribe to the notification `MMRegistrationUpdated` to be notified as the registration succeeded." UserInfo={NSLocalizedDescription=The application instance is not registered on the server yet. The registration will be performed eventually. Subscribe to the notification `MMRegistrationUpdated` to be notified as the registration succeeded.}

I guess It's related to the race condition and which you have mentioned previously. The scenario is while I try to personlise there's no registration on the server. 

Can you provide a few things on your upcoming release: 
1. Provide an observing method where I will have a trigger of registration and I'll set registration on app launch.  (l.e. : `MMRegistrationSuccessfullyOnServer` or something else.)
2. Provide any existing method by which we can register on the server on the app launch. 

Once we have registered already on the app launch, we can directly personalize without any race conditional error. 

Hope you understand my point and expecting your soonest response.

**Comment by kas-kad** [comment]
Hello @akshardarji. I will think about it and get back to you with updates.

**Comment by kas-kad** [comment]
@akshardarji 
1. You can observe already existing event by notification name `MMNotificationRegistrationUpdated`. It's being posted when the registration is updated on backend server. The notification is posted during the registration process, after a current APNs device token is stored on the server and the new Push Registration Id for the current user is generated. The userInfo dictionary contains the following keys: `MMNotificationKeyRegistrationInternalId` - contains a Push Registration Id string for the registered user. If the value under the key `MMNotificationKeyRegistrationInternalId` is not nil, that means the registration has been succeeded.

2. Introducing an explicit API for triggering registration won't help much because the registration process depends on Device Token which is being provided to the application in asynchronous manner. If the application has not yet received Device Token from iOS (Apple server), there is no point to invoke explicit registration process.

What I would recommend you to do is a combination of these two:
- Observing `MMNotificationRegistrationUpdated` notification to know at which moment the registration is done;
- Checking `MobileMessaging.gerInstallation().pushRegistrationId` property value in order to define whether or not the registration is available at current moment.
