### ISSUE TITLE
Can't use SPM (Swift Package Manager) to add this to my project

### ISSUE THREAD

**Issue by jesaavedrav** [infobip/mobile-messaging-sdk-ios#36]
Hello.

I was wondering if you could add SPM support for this library

* MobileMessaging SDK version: 9.2.10
* Xcode version: 13.2.1
* Your application language: Swift
* Cocoapods version: NaN

**Comment by riskpp** [comment]
Hello @jesaavedrav, we already had such question here  - https://github.com/infobip/mobile-messaging-sdk-ios/issues/17

**Comment by riskpp** [comment]
Hello @jesaavedrav, integration via SPM is supported since [10.22.0 version](https://github.com/infobip/mobile-messaging-sdk-ios/releases/tag/10.22.0), please check the FAQ page - [Integration-via-Swift-Package-Manager](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Integration-via-Swift-Package-Manager) for more information.
